version: '3'
services:
  bastion:
    build:
      context: .
      dockerfile: Dockerfile-bastion
    ports:
      - "2222:22"
    networks:
      - private_network
      - public_network
  ic1:
    build:
      context: .
      dockerfile: Dockerfile-ic
    environment:
      CONTAINER_NAME: ic1
    networks:
      - private_network
    depends_on:
      - load_balancer
    links:
      - load_balancer
  ic2:
    build:
      context: .
      dockerfile: Dockerfile-ic
    environment:
      CONTAINER_NAME: ic2
    networks:
      - private_network
    depends_on:
      - load_balancer
    links:
      - load_balancer
  load_balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./lb_nginx.conf:/etc/nginx/nginx.conf
    networks:
      - private_network
      - public_network
networks:
  private_network:
    internal: true
  public_network:
