FROM alpine:latest
RUN apk update && apk add openssh
RUN ssh-keygen -A
RUN adduser -D user
RUN echo "user:password" | chpasswd
COPY id_rsa /home/user/.ssh/id_rsa
RUN chown -R user:user /home/user/.ssh
RUN chmod 600 /home/user/.ssh/id_rsa

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
